<?php
/**
 * Cityland Online Property Bidding System — configuration.
 *
 * Copy this file to app/config.php (the web installer does this for you)
 * and fill in the values. NEVER commit app/config.php to version control.
 */
return [
    // ------------------------------------------------------------------
    // Application
    // ------------------------------------------------------------------
    'app' => [
        // Full public URL of the site WITHOUT trailing slash, e.g. https://bidding.cityland.com.ph
        // or https://www.example.com/bidding if installed in a sub-folder.
        'url'       => 'https://bidding.example.com',
        'timezone'  => 'Asia/Manila',
        // 'production' for the live site. 'testing' shows a TEST ENVIRONMENT banner, enables the
        // test mailbox (/dev/mailbox.php) and admin test tools. NEVER use 'testing' on the live site.
        'env'       => 'production',
        // Set to true only while troubleshooting. Never on a live site.
        'debug'     => false,
        // Redirect all http:// traffic to https:// and send HSTS header.
        'force_https' => true,
        // Long random string (64+ chars). Used for hashing/signing. Generated by the installer.
        'secret_key' => 'CHANGE_ME_TO_A_LONG_RANDOM_STRING',
        // Absolute path to the private storage folder (uploads, backups, logs).
        // Best practice on cPanel: move it OUTSIDE public_html, e.g. /home/USER/cityland_storage
        'storage_path' => __DIR__ . '/../storage',
        // Maximum upload size per file in megabytes (also check PHP upload_max_filesize).
        'max_upload_mb' => 10,
    ],

    // ------------------------------------------------------------------
    // Database (cPanel > MySQL Databases)
    // ------------------------------------------------------------------
    'db' => [
        'host'     => 'localhost',
        'port'     => 3306,
        'name'     => 'cpaneluser_bidding',
        'user'     => 'cpaneluser_bidding',
        'pass'     => '',
        'charset'  => 'utf8mb4',
    ],

    // ------------------------------------------------------------------
    // Email (SMTP) — cPanel email account or third-party (SendGrid, Mailgun, SES, Gmail/Workspace, M365)
    // driver: 'smtp' (recommended), 'mail' (PHP mail()), or 'log' (write emails to storage/logs/mail.log; testing only)
    // encryption: 'ssl' (port 465), 'tls' (STARTTLS, port 587) or '' (none, port 25 — not recommended)
    // ------------------------------------------------------------------
    'mail' => [
        'driver'     => 'smtp',
        'host'       => 'mail.example.com',
        'port'       => 465,
        'encryption' => 'ssl',
        'username'   => 'bidding@example.com',
        'password'   => '',
        'from_email' => 'bidding@example.com',
        'from_name'  => 'Cityland Property Bidding',
        'timeout'    => 15,
    ],

    // ------------------------------------------------------------------
    // SMS (mobile OTP). provider: 'none', 'semaphore' (semaphore.co, PH) or 'http' (generic GET/POST gateway)
    // ------------------------------------------------------------------
    'sms' => [
        'provider'    => 'none',
        'api_key'     => '',
        'sender_name' => 'CITYLAND',
        // For provider 'http': placeholders {to} {message} {api_key} {sender}
        'http_url'    => '',
        'http_method' => 'POST',
    ],

    // ------------------------------------------------------------------
    // Human verification. provider: 'builtin' (image/math CAPTCHA, no external calls),
    // 'recaptcha' (Google reCAPTCHA v2 checkbox) or 'turnstile' (Cloudflare Turnstile)
    // ------------------------------------------------------------------
    'captcha' => [
        'provider'   => 'builtin',
        'site_key'   => '',
        'secret_key' => '',
    ],

    // ------------------------------------------------------------------
    // Security
    // ------------------------------------------------------------------
    'security' => [
        'max_login_attempts'   => 5,    // per account within the window
        'max_ip_attempts'      => 20,   // per IP within the window
        'lockout_minutes'      => 15,
        'session_idle_minutes' => 30,
        'session_absolute_hours' => 8,
        'password_min_length'  => 10,
        // Cron key for calling cron.php over HTTP (?key=...). Generated by installer.
        'cron_key'             => 'CHANGE_ME',
        // If behind Cloudflare / a reverse proxy, list trusted proxy IPs so the real client IP is used.
        'trusted_proxies'      => [],
    ],
    // Online license renewal: the vendor's PayMongo renewal portal. Leave '' to use the built-in default.
    'license' => [
        'renew_url' => '',
    ],
];
