<?php
/**
 * TEST ENVIRONMENT tool — never use on the live site.
 *
 *   php tools/testenv.php setup   Create test config (if missing), install the database (if empty) and load test data
 *   php tools/testenv.php reset   Wipe the TEST database + uploads and reload fresh test data
 *   php tools/testenv.php accounts  Print the test login accounts
 *
 * Options (or matching environment variables), used when creating the test config:
 *   --url=http://localhost:8080   (APP_URL)        --db-host=127.0.0.1 (DB_HOST)   --db-port=3306 (DB_PORT)
 *   --db-name=cityland_test       (DB_NAME)        --db-user=root      (DB_USER)   --db-pass=     (DB_PASS)
 *   --mail=log|smtp               (MAIL_DRIVER)    --smtp-host=        (SMTP_HOST) --smtp-port=   (SMTP_PORT)
 *   --storage=/path/to/storage    (STORAGE_PATH)   --config=/path/to/config.php (CL_CONFIG, default app/config.php)
 */
declare(strict_types=1);
if (PHP_SAPI !== 'cli') {
    exit("CLI only\n");
}

$cmd = $argv[1] ?? 'help';
$opts = [];
foreach (array_slice($argv, 2) as $a) {
    if (preg_match('/^--([a-z-]+)=(.*)$/', $a, $m)) {
        $opts[$m[1]] = $m[2];
    }
}
$opt = static function (string $name, string $env, string $default) use ($opts): string {
    if (isset($opts[$name])) {
        return $opts[$name];
    }
    $v = getenv($env);
    return ($v !== false && $v !== '') ? $v : $default;
};

$root = dirname(__DIR__);
$configFile = $opt('config', 'CL_CONFIG', $root . '/app/config.php');
putenv('CL_CONFIG=' . $configFile);

if ($cmd === 'help' || !in_array($cmd, ['setup', 'reset', 'accounts'], true)) {
    $doc = (string) file_get_contents(__FILE__);
    preg_match('#/\*\*(.*?)\*/#s', $doc, $m);
    echo preg_replace('/^\s*\* ?/m', '', $m[1] ?? '') . "\n";
    exit($cmd === 'help' ? 0 : 1);
}

// ---------------------------------------------------------------- 1. test config
if (!is_file($configFile)) {
    if ($cmd === 'accounts') {
        exit("No config found. Run: php tools/testenv.php setup\n");
    }
    $storage = $opt('storage', 'STORAGE_PATH', $root . '/storage');
    $config = [
        'app' => [
            'url' => rtrim($opt('url', 'APP_URL', 'http://localhost:8080'), '/'), 'timezone' => 'Asia/Manila', 'env' => 'testing',
            'debug' => true, 'force_https' => false, 'secret_key' => bin2hex(random_bytes(32)), 'storage_path' => $storage, 'max_upload_mb' => 10,
        ],
        'db' => ['host' => $opt('db-host', 'DB_HOST', '127.0.0.1'), 'port' => (int) $opt('db-port', 'DB_PORT', '3306'), 'name' => $opt('db-name', 'DB_NAME', 'cityland_test'),
            'user' => $opt('db-user', 'DB_USER', 'root'), 'pass' => $opt('db-pass', 'DB_PASS', ''), 'charset' => 'utf8mb4'],
        'mail' => ['driver' => $opt('mail', 'MAIL_DRIVER', 'log'), 'host' => $opt('smtp-host', 'SMTP_HOST', 'localhost'), 'port' => (int) $opt('smtp-port', 'SMTP_PORT', '1025'),
            'encryption' => '', 'username' => '', 'password' => '', 'from_email' => 'bidding@test.local', 'from_name' => 'Cityland Bidding (TEST)', 'timeout' => 10],
        'sms' => ['provider' => 'none', 'api_key' => '', 'sender_name' => 'CITYLAND', 'http_url' => '', 'http_method' => 'POST'],
        'captcha' => ['provider' => 'builtin', 'site_key' => '', 'secret_key' => ''],
        'security' => ['max_login_attempts' => 5, 'max_ip_attempts' => 50, 'lockout_minutes' => 15, 'session_idle_minutes' => 60,
            'session_absolute_hours' => 12, 'password_min_length' => 10, 'cron_key' => bin2hex(random_bytes(16)), 'trusted_proxies' => []],
    ];
    if (!is_dir(dirname($configFile))) {
        mkdir(dirname($configFile), 0750, true);
    }
    file_put_contents($configFile, "<?php\n// TEST ENVIRONMENT configuration generated by tools/testenv.php on " . date('c') . "\n// app.env = 'testing' — NEVER deploy this file to the live site.\nreturn " . var_export($config, true) . ";\n");
    foreach (['uploads', 'backups', 'logs', 'sessions'] as $d) {
        @mkdir($storage . '/' . $d, 0770, true);
    }
    echo "Created test config: {$configFile}\n";
}

$GLOBALS['__testenv_cfg'] = require $configFile;
if (($GLOBALS['__testenv_cfg']['app']['env'] ?? 'production') !== 'testing') {
    fwrite(STDERR, "REFUSED: {$configFile} is not a TEST configuration (app.env must be 'testing'). This tool never touches a live database.\n");
    exit(2);
}

// ---------------------------------------------------------------- 2. database (create DB if missing, wait until reachable)
$c = $GLOBALS['__testenv_cfg']['db'];
$pdo = null;
for ($try = 1; $try <= 60; $try++) {
    try {
        $pdo = new PDO("mysql:host={$c['host']};port={$c['port']};charset=utf8mb4", $c['user'], $c['pass'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
        break;
    } catch (PDOException $e) {
        if ($try === 1) {
            echo "Waiting for database {$c['host']}:{$c['port']} ...\n";
        }
        if ($try === 60) {
            fwrite(STDERR, 'Database not reachable: ' . $e->getMessage() . "\n");
            exit(1);
        }
        sleep(2);
    }
}
try {
    $pdo->exec('CREATE DATABASE IF NOT EXISTS `' . str_replace('`', '', $c['name']) . '` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
} catch (PDOException) {
    // user may lack CREATE privilege; the database must then already exist
}

require $root . '/app/bootstrap.php';

// ---------------------------------------------------------------- 3. commands
$printAccounts = static function (): void {
    echo "\n  TEST ACCOUNTS\n  -------------\n";
    echo "  Admin portal: " . url('admin/') . "   (password for all admins: " . TestEnv::ADMIN_PASSWORD . ")\n";
    foreach (TestEnv::ADMINS as [$name, $email, $role]) {
        printf("    %-26s %s\n", $email, Rbac::label($role));
    }
    echo "  Bidder site:  " . url('') . "   (password for all bidders: " . TestEnv::BIDDER_PASSWORD . ")\n";
    foreach (TestEnv::BIDDERS as [$name, , $email, , $state]) {
        printf("    %-26s %s (%s)\n", $email, $name, $state);
    }
    echo "  Test mailbox: " . url('dev/mailbox.php') . "   (all emails & verification codes)\n\n";
};

try {
    if ($cmd === 'accounts') {
        $printAccounts();
        exit(0);
    }
    if ($cmd === 'reset') {
        foreach (TestEnv::reset() as $line) {
            echo "  - {$line}\n";
        }
        echo "Test data reset complete.\n";
    } else { // setup
        if (!TestEnv::hasSchema()) {
            echo '  - ' . TestEnv::installSchema() . "\n";
        }
        if (!(int) DB::val('SELECT COUNT(*) FROM admins')) {
            foreach (TestEnv::seed() as $line) {
                echo "  - {$line}\n";
            }
        } else {
            echo "  - Existing test data kept (use 'reset' to start over).\n";
        }
        echo "Test environment ready.\n";
    }
    $printAccounts();
} catch (Throwable $e) {
    fwrite(STDERR, 'ERROR: ' . $e->getMessage() . "\n");
    exit(1);
}
